export const programs = [
  {
    id: "postgraduate-masters",
    category: "Postgraduate Diplomas & Master’s Programmes",
    badge: "Advanced Studies",
    description: "Advanced programmes for graduates and professionals to deepen expertise and expand leadership potential.",
    items: [
      {
        title: "Postgraduate Diploma Programs",
        duration: "9 – 24 months",
        mode: "Blended",
        description: "Specialized postgraduate qualifications for career advancement.",
        highlights: [
          "Business Administration",
          "Public Administration & Management",
          "Educational Planning & Management",
          "Human Resource Management",
          "Finance",
          "Procurement & Logistics Management",
          "Project Planning & Management",
          "Monitoring and Evaluation",
          "Public Health",
        ],
      },
      {
        title: "Master’s Degree Programs",
        duration: "9 – 24 months",
        mode: "Blended",
        description: "Comprehensive master's degrees for strategic leadership.",
        highlights: [
          "Master of Business Administration (MBA)",
          "Master of Public Administration & Management (MPAM)",
          "Master of Science in Human Resource Management (MSHRM)",
          "Master of Science in Finance (MSF)",
          "Master of Science in Procurement & Logistics Management (MSPLM)",
          "Master of Arts in Economics (MAE)",
          "Master of Educational Planning & Management (MEPM)",
          "Master of Information Technology (MIT)",
          "Master of Development Studies (MDS)",
          "Master of Information Systems (MIS)",
          "Master of Project Planning & Management (MPPM)",
          "Master of Science in Public Health (MSPH)",
        ],
      },
    ],
  },
  {
    id: "professional-cpau",
    category: "Professional Courses",
    badge: "Certification",
    description: "Tailored training for certifications, professional alignment, and continuing professional development (CPD).",
    items: [
      {
        title: "CPAU Professional Exams (Levels I - IV)",
        duration: "Weeks-months flexible",
        mode: "Evening / Weekend / Online",
        description: "Comprehensive preparation for CPA Uganda examinations. Covers Level I (Test of Competence), Level II (Test of Technical Skills), Level III (Test of Professional Skills), and Level IV (Test of Professional Expertise).",
        highlights: [
          "Level I: Financial Accounting, Economics, Law, Cost Accounting",
          "Level II: Financial Reporting, Auditing, Taxation, Management",
          "Level III: Adv. Financial Reporting, Public FM, Strategy, Audit Practice",
          "Level IV: Integration of Knowledge",
        ],
      },
      {
        title: "Certified Financial Accountant Workshop",
        duration: "Flexible",
        mode: "Flexible",
        description: "Practical workshop for financial accounting professionals focusing on industry scenarios.",
        highlights: ["Case studies", "Industry scenarios", "Professional ethics"],
      },
      {
        title: "Corporate Governance & Ethics for Managers",
        duration: "Flexible",
        mode: "Flexible",
        description: "Training on corporate governance principles, board roles, and ethical decision making.",
        highlights: ["Board roles", "Ethical frameworks", "Compliance"],
      },
      {
        title: "Business Data Analytics for Professionals",
        duration: "Flexible",
        mode: "Flexible",
        description: "Data analysis skills tailored for business decision-making and reporting.",
        highlights: ["Data visualization", "Reporting", "Business intelligence"],
      },
      {
        title: "Professional Short-Course in Taxation & Compliance",
        duration: "Flexible",
        mode: "Flexible",
        description: "Focused course on tax laws, planning, and regulatory compliance requirements.",
        highlights: ["Tax planning", "Regulatory compliance", "Filing procedures"],
      },
    ],
  },
  {
    id: "short-business-courses",
    category: "Short Business Courses",
    badge: "Skill Upgrade",
    description: "High-impact courses for key business skills, leadership, and entrepreneurship in a short timeframe.",
    items: [
      {
        title: "One-Month Short Courses",
        duration: "≈ 4-5 weeks",
        mode: "Flexible",
        description: "Intensive introductory courses for quick skill acquisition.",
        highlights: [
          "Public Speaking & Presentation Skills",
          "Job Interview Preparation & Career Networking",
          "Introductory Financial Management for Non-Finance Individuals",
          "Record Keeping & Information Management",
          "Basics of Tax Compliance & Return Filing",
          "Introduction to Project Planning & Management",
          "Monitoring & Evaluation (M&E) Fundamentals",
          "Digital Literacy: Microsoft Office & Online Collaboration",
          "Customer Service & Communication Skills",
          "Entrepreneurship Skills: From Idea to Business Plan",
          "Time Management & Productivity Techniques",
          "Social Media Marketing for Small Businesses",
          "Basic Accounting & Bookkeeping",
          "Records Management Systems (Manual & Digital)",
          "Introduction to Data Analysis (Excel)",
          "Strategic Customer Service & Client Relations",
          "Digital Marketing & E-Commerce for SMEs",
          "Leadership & Change Management in SMEs",
        ],
      },
      {
        title: "Three-Month Advanced Courses",
        duration: "≈ 12-13 weeks",
        mode: "Flexible",
        description: "Comprehensive courses for in-depth professional development.",
        highlights: [
          "Advanced Public Speaking & Leadership Communication",
          "Professional Job Interview & Career Development",
          "Financial Management, Budgeting & Control",
          "Comprehensive Record Keeping & Information Systems",
          "Taxation, Compliance & Strategic Return Filing",
          "Project Management & Full M&E Cycle",
          "IT & Digital Transformation for Business",
          "Strategic Marketing & Digital Advertising",
          "Human Resource Management & OD",
          "Business Process Improvement & Internal Controls",
          "Strategic Planning, Change Management & Leadership",
          "Data Analytics & Reporting for Business Intelligence",
          "Risk Management & Governance",
          "Supply Chain, Procurement & Logistics",
          "Entrepreneurship Boot-camp: Build, Launch & Scale",
          "Foundations of AI for Business Leaders",
          "Leadership & Team Dynamics in Hybrid Environments",
          "Personal Branding & Professional Presence",
        ],
      },
    ],
  },

];
